- name: Install latest Apache server
  hosts: prod,dev
  become: true
  tasks:
          - name: Install apache httpd
            apt:
              name: apache2
              update_cache: yes
              state: present


          - name: Copy file with owner and permissions
            copy:
              src: /tmp/index.html
              dest: /var/www/html/index.html


          - name: Start service apache, if not started
            service:
              name: apache2
              state: started
              enabled: yes
