---
- name: create users
  hosts: all
  vars_files:
    - fvars/users_list.yml
    - vault/users_pass.yml
  become: true
  tasks:
       - name: ensure group devops
         group:
            name: devops
            state: present
         when: "'dev' in group_names"

       - name: Create developers
         user:
           name: "{{ item.username }}"
           group: devops
           password: "{{ pw_dev |  password_hash('sha512') }}"
         when:
                 - "'dev' in group_names"
                 - ('developer' in item.job) 
         loop: "{{ users }}"   


       - name: ensure managers group 
         group: 
            name: managers
            state: present
         when: "'prod' in group_names"    
           
       - name: create managers
         user:
           name: "{{ item.username }}"
           group: managers
           password: "{{ pw_mgr | password_hash('sha512') }}"
         when: 
              - "'prod' in group_names"
              - ('manager' in item.job)
         loop: "{{ users }}"                     
